[package]
name = "aoc-rs-template"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
reqwest = { version = "0.12.9", features = ["gzip"] }
tokio = { version = "1.41.1", features = ["full"] }
